name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # build
      - run: "& $env:GITHUB_WORKSPACE/build.ps1"
        shell: pwsh
      # upload
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SophosCentral.zip"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
